[tool.poetry]
name = "lime-uow"
version = "0.1.41"
description = "Framework to support the Unit-of-Work pattern"
authors = ["Mark Stefanovic <markstefanovic@hotmail.com>"]
include = ["lime_uow/py.typed"]
license = "MIT"
repository = "https://github.com/MarkStefanovic/lime-uow"

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "^1.3.19"
pyodbc = "^4.0.30"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
python-dotenv = "^0.15.0"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
