[tool.poetry]
name = "devcli"
version = "0.1.2"
description = ""
authors = ["Job de Noo <jgdenoo@gmail.com>"]
homepage = "https://github.com/devnoo/dev-cli/"
repository = "https://github.com/devnoo/dev-cli/"
packages = [
    { include = "devcli" },
    { include = "devcli_gitlab" },
    { include = "devcli_poetry_install" },
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-gitlab = "^2.5.0"
gitlabber = "^1.1.0"
python-graphql-client = "^0.4.0"
click = "^7.1.2"
cachetools = "^4.1.1"
"ruamel.yaml" = "^0.16.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
devcli = 'devcli:run'